import { Experience, BookingRequest } from '@/types';

export const experiences: Experience[] = [
    {
        id: '1',
        title: 'Visite Culturelle du Centre-Ville de Ouagadougou',
        description: 'Découvrez le cœur battant de la capitale burkinabè avec ses marchés animés et son architecture unique.',
        longDescription: 'Plongez dans l\'authenticité de Ouagadougou à travers cette visite guidée complète. Explorez les marchés traditionnels, découvrez l\'artisanat local, et imprégnez-vous de la culture mossi. Cette expérience vous emmènera à travers les sites historiques et culturels majeurs de la capitale.',
        city: 'Ouagadougou',
        type: 'experience',
        category: 'Culture',
        price: 25000,
        duration: '4 heures',
        images: [
            'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=800',
            'https://images.unsplash.com/photo-1523906630133-f6934a1ab2b9?w=800',
        ],
        highlights: [
            'Visite du marché de Rood-Woko',
            'Découverte du Monument des Martyrs',
            'Visite de la Grande Mosquée',
            'Dégustation de plats locaux',
        ],
        included: [
            'Guide francophone expérimenté',
            'Transport climatisé',
            'Eau minérale',
            'Dégustation culinaire',
        ],
        notIncluded: [
            'Repas complet',
            'Souvenirs personnels',
            'Pourboires',
        ],
        createdAt: new Date('2025-11-20'),
        featured: true,
    },
    {
        id: '2',
        title: 'Safari Urbain à Bobo-Dioulasso',
        description: 'Explorez la deuxième ville du Burkina Faso, son architecture coloniale et sa vieille mosquée en banco.',
        longDescription: 'Bobo-Dioulasso, capitale économique et culturelle de l\'ouest du Burkina Faso, vous dévoile ses secrets. De la vieille mosquée de Dioulassoba construite en banco à la visite de la vieille ville de Kibidwé, cette journée sera riche en découvertes.',
        city: 'Bobo-Dioulasso',
        type: 'experience',
        category: 'Culture',
        price: 30000,
        duration: '6 heures',
        images: [
            'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800',
            'https://images.unsplash.com/photo-1581888227599-779811939961?w=800',
        ],
        highlights: [
            'Mosquée de Dioulassoba (XVe siècle)',
            'Vieille ville de Kibidwé',
            'Visite d\'une brasserie artisanale',
            'Marché de Bobo',
        ],
        included: [
            'Guide local expert',
            'Transport',
            'Déjeuner traditionnel',
            'Eau et rafraîchissements',
        ],
        notIncluded: [
            'Achats personnels',
            'Boissons alcoolisées supplémentaires',
        ],
        createdAt: new Date('2025-11-22'),
        featured: true,
    },
    {
        id: '3',
        title: 'Restaurant Le Verdoyant',
        description: 'Savourez une cuisine burkinabè authentique dans un cadre verdoyant et paisible.',
        longDescription: 'Le Verdoyant est l\'une des meilleures adresses de Ouagadougou pour découvrir la gastronomie locale. Dans un jardin tropical, dégustez des plats traditionnels revisités avec des produits frais du marché.',
        city: 'Ouagadougou',
        type: 'activity',
        category: 'Restaurant',
        price: 8000,
        duration: '2 heures',
        images: [
            'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
        ],
        highlights: [
            'Cuisine burkinabè authentique',
            'Cadre verdoyant',
            'Produits locaux frais',
            'Ambiance conviviale',
        ],
        included: [
            'Menu complet',
            'Boisson non-alcoolisée',
        ],
        notIncluded: [
            'Boissons alcoolisées',
            'Desserts supplémentaires',
        ],
        createdAt: new Date('2025-11-25'),
        featured: false,
    },
    {
        id: '4',
        title: 'Atelier de Poterie Traditionnelle',
        description: 'Apprenez les techniques ancestrales de la poterie burkinabè avec un artisan expert.',
        longDescription: 'Participez à un atelier authentique de poterie et découvrez les techniques traditionnelles transmises de génération en génération. Créez votre propre pièce sous les conseils d\'un maître potier.',
        city: 'Ouagadougou',
        type: 'activity',
        category: 'Atelier',
        price: 15000,
        duration: '3 heures',
        images: [
            'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800',
        ],
        highlights: [
            'Apprentissage avec un maître artisan',
            'Création de votre pièce unique',
            'Techniques traditionnelles',
            'Emportez votre création',
        ],
        included: [
            'Matériel complet',
            'Instruction en français',
            'Votre création',
            'Rafraîchissements',
        ],
        notIncluded: [
            'Transport',
        ],
        createdAt: new Date('2025-11-26'),
        featured: true,
    },
    {
        id: '5',
        title: 'Restaurant Chez Aicha',
        description: 'Dégustez les meilleurs grillades et plats locaux de Bobo-Dioulasso.',
        longDescription: 'Chez Aicha est une institution à Bobo-Dioulasso. Ce restaurant familial propose depuis 20 ans les meilleures grillades de la ville dans une ambiance chaleureuse et accueillante.',
        city: 'Bobo-Dioulasso',
        type: 'activity',
        category: 'Restaurant',
        price: 7000,
        duration: '2 heures',
        images: [
            'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
        ],
        highlights: [
            'Grillades réputées',
            'Ambiance familiale',
            'Prix abordables',
            'Plats généreux',
        ],
        included: [
            'Repas complet',
            'Eau minérale',
        ],
        notIncluded: [
            'Boissons supplémentaires',
        ],
        createdAt: new Date('2025-11-27'),
        featured: false,
    },
    {
        id: '6',
        title: 'Atelier de Percussion Africaine',
        description: 'Initiez-vous au djembé et aux rythmes traditionnels avec des musiciens professionnels.',
        longDescription: 'Plongez dans l\'univers fascinant des percussions africaines. Cet atelier vous permettra d\'apprendre les bases du djembé et de découvrir les rythmes traditionnels burkinabè dans une ambiance conviviale.',
        city: 'Bobo-Dioulasso',
        type: 'activity',
        category: 'Atelier',
        price: 12000,
        duration: '2 heures',
        images: [
            'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?w=800',
        ],
        highlights: [
            'Musiciens professionnels',
            'Instruments fournis',
            'Tous niveaux acceptés',
            'Ambiance conviviale',
        ],
        included: [
            'Instruments',
            'Cours en français',
            'Rafraîchissements',
        ],
        notIncluded: [
            'Transport',
        ],
        createdAt: new Date('2025-11-28'),
        featured: true,
    },
    {
        id: '7',
        title: 'Spa Harmonie - Massage Traditionnel',
        description: 'Offrez-vous un moment de détente absolue avec nos massages aux huiles de karité.',
        longDescription: 'Le Spa Harmonie vous propose une expérience de bien-être unique au cœur de Ouagadougou. Nos thérapeutes qualifiés utilisent des techniques traditionnelles africaines combinées avec les bienfaits du beurre de karité du Burkina Faso pour vous offrir un moment de relaxation profonde.',
        city: 'Ouagadougou',
        type: 'activity',
        category: 'Spa',
        price: 20000,
        duration: '1h30',
        images: [
            'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800',
        ],
        highlights: [
            'Massage aux huiles de karité bio',
            'Thérapeutes certifiés',
            'Ambiance zen et relaxante',
            'Produits naturels locaux',
        ],
        included: [
            'Massage complet 1h30',
            'Tisane de bienvenue',
            'Serviettes et peignoir',
            'Accès au salon de repos',
        ],
        notIncluded: [
            'Soins supplémentaires',
            'Transport',
        ],
        createdAt: new Date('2025-11-29'),
        featured: true,
    },
    {
        id: '8',
        title: 'Spa Zenith - Rituel Africain',
        description: 'Un rituel complet de beauté et bien-être inspiré des traditions africaines.',
        longDescription: 'Découvrez le rituel africain du Spa Zenith à Bobo-Dioulasso. Ce soin complet comprend un gommage au savon noir, un enveloppement au beurre de karité et un massage relaxant. Une expérience sensorielle unique qui vous reconnecte avec les traditions de beauté africaines.',
        city: 'Bobo-Dioulasso',
        type: 'activity',
        category: 'Spa',
        price: 35000,
        duration: '2h30',
        images: [
            'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800',
        ],
        highlights: [
            'Gommage au savon noir',
            'Enveloppement karité',
            'Massage relaxant',
            'Soin visage offert',
        ],
        included: [
            'Rituel complet 2h30',
            'Produits 100% naturels',
            'Thé et collation',
            'Espace détente',
        ],
        notIncluded: [
            'Soins capillaires',
            'Transport',
        ],
        createdAt: new Date('2025-11-30'),
        featured: true,
    },
    {
        id: '9',
        title: 'Atelier Tissage Faso Dan Fani',
        description: 'Apprenez l\'art du tissage traditionnel burkinabè avec des artisans experts.',
        longDescription: 'Le Faso Dan Fani est le tissu traditionnel du Burkina Faso, symbole de fierté nationale. Dans cet atelier, vous découvrirez les techniques ancestrales de tissage sur métier traditionnel et créerez votre propre bande de tissu à emporter.',
        city: 'Ouagadougou',
        type: 'activity',
        category: 'Atelier',
        price: 18000,
        duration: '4 heures',
        images: [
            'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        ],
        highlights: [
            'Métier à tisser traditionnel',
            'Artisan expert',
            'Création personnelle',
            'Histoire du Faso Dan Fani',
        ],
        included: [
            'Formation complète',
            'Matériel fourni',
            'Votre création',
            'Certificat de participation',
        ],
        notIncluded: [
            'Transport',
            'Repas',
        ],
        createdAt: new Date('2025-12-01'),
        featured: false,
    },
];

export const bookingRequests: BookingRequest[] = [];
